version: '3'
volumes:
  db:

services:
  db:
    image: postgres
    container_name: app_financial_db
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
